language: r
dist: xenial
cache:
  packages: true
  directories:
    - /home/travis/.cache/pip
r:
  - release
  - devel
env:
  - PYTHON=3.6
  - PYTHON=3.7
install:
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo add-apt-repository --remove ppa:kirillshkrogalev/ffmpeg-next  # broken
  - sudo apt-get update -q
  - sudo apt-get install python$PYTHON -y
  - python$PYTHON -m pip install flit future-fstrings hg+https://bitbucket.org/rpy2/rpy2
  - flit install --extras=all
script:
  - PYTHONPATH=. pytest
bioc_packages:
  - SingleCellExperiment
  - scRNAseq
addons:
  apt:
    sources:
      - deadsnakes
