language: r
dist: xenial
cache:
  packages: true
  directories:
    - /home/travis/.cache/pip
r:
  - release
  - devel
env:
  - PYTHON=3.6
  - PYTHON=3.7
install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update -q  -o Dir::Etc::sourcelist="sources.list.d/deadsnakes-ubuntu-ppa-xenial.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
  - sudo apt-get install -y python$PYTHON python$PYTHON-venv
  - sudo python$PYTHON -m ensurepip
  - sudo python$PYTHON -m pip install flit future-fstrings hg+https://bitbucket.org/rpy2/rpy2
  - sudo FLIT_ROOT_INSTALL=1 flit install --extras=all
script:
  - PYTHONPATH=. pytest
bioc_packages:
  - SingleCellExperiment
  - scRNAseq
