language: r
dist: xenial
cache:
  packages: true
  directories:
    - /home/travis/.cache/pip
r:
  - release
  - devel
env:
  - PYTHON=3.6
  - PYTHON=3.7
before_install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
install:
  - sudo apt-get install -y python$PYTHON python$PYTHON-venv
  - sudo python$PYTHON -m ensurepip
  - sudo python$PYTHON -m pip install flit future-fstrings hg+https://bitbucket.org/rpy2/rpy2
  - flit install --extras=all
script:
  - PYTHONPATH=. pytest
bioc_packages:
  - SingleCellExperiment
  - scRNAseq
