language: r
dist: xenial
cache:
  packages: true
  directories:
    - /home/travis/.cache/pip

# matrix
r:
  - release
  - devel
env:
  - PYTHON=3.6
  - PYTHON=3.7

bioc_packages: # install R packages
  - SingleCellExperiment
  - scRNAseq
before_install: # install python
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update -q  -o Dir::Etc::sourcelist="sources.list.d/deadsnakes-ubuntu-ppa-xenial.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
  - sudo apt-get install -y python$PYTHON python$PYTHON-venv
  - sudo -H python$PYTHON -m ensurepip
install: # install test packages
  - sudo -H python$PYTHON -m pip install flit future-fstrings get_version hg+https://bitbucket.org/rpy2/rpy2
  - python$PYTHON -m rpy2.situation
  - sudo -H FLIT_ROOT_INSTALL=1 flit install --extras=all

script:
  - PYTHONPATH=. pytest
