language: python
dist: xenial
cache: pip
python:
  - 3.6
  - 3.7
install:
  - pip install flit future-fstrings hg+https://bitbucket.org/rpy2/rpy2
  - flit install --extras=all
script:
  - PYTHONPATH=. pytest
